# values.yaml
replicaCount: 1

backend:
  image:
    repository: mohanadnassar/backend
    tag: "2024-08-13.06"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000

frontend:
  image:
    repository: mohanadnassar/frontend
    tag: "2024-08-13.04"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80

ingress:
  enabled: true
  host: dhbw-appstore.com
  paths:
    - path: /
      backend: frontend-service
      port: 80
    - path: /apps
      backend: backend-service
      port: 8000
    - path: /users
      backend: backend-service
      port: 8000
    - path: /auth
      backend: backend-service
      port: 8000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

serviceAccount:
  create: true
  automount: true
  name: "app-deployer"
