apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: appstore-chart
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
spec:
  interval: 5m0s
  chart:
    spec:
      chart: ./appstore-chart
      sourceRef:
        kind: GitRepository
        name: dhbw-appstore
        namespace: flux-system
  values:
    serviceAccount:
      create: true
      automount: true
      name: "app-deployer"
    replicaCount: 1
    backend:
      image:
        repository: mohanadnassar/backend
        tag: "2024-08-13.07"
        pullPolicy: IfNotPresent
      service:
        type: ClusterIP
        port: 8000
    frontend:
      image:
        repository: mohanadnassar/frontend
        tag: "2024-08-13.04"
        pullPolicy: IfNotPresent
      service:
        type: ClusterIP
        port: 80
    ingress:
      enabled: true
      host: dhbw-appstore.com
      paths:
        - path: /
          backend: frontend-service
          port: 80
        - path: /apps
          backend: backend-service
          port: 8000
        - path: /users
          backend: backend-service
          port: 8000
        - path: /auth
          backend: backend-service
          port: 8000
