---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dhbw-appstore
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/MohanadNasar/DHBW-AppStore
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/MohanadNasar/DHBW-AppStore
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: dhbw-appstore
    namespace: flux-system
