apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: dhbw-appstore
    namespace: flux-system
  resources:
    - gotk-components.yaml
    - gotk-sync.yaml
  patches:
    - patch: |
        - op: add
          path: /spec/pruneResources
          value:
            - apiVersion: rbac.authorization.k8s.io/v1
              kind: Role
              name: app-deployer-role
              namespace: default
            - apiVersion: rbac.authorization.k8s.io/v1
              kind: RoleBinding
              name: app-deployer-binding
              namespace: default
      target:
        kind: Kustomization
        name: flux-system
