apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app.kubernetes.io/managed-by: Helm
    app: backend
  annotations:
    meta.helm.sh/release-name: appstore-chart
    meta.helm.sh/release-namespace: default
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
  type: {{ .Values.backend.service.type }}
