#backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app.kubernetes.io/managed-by: Helm
    app: backend
  annotations:
    meta.helm.sh/release-name: appstore-chart
    meta.helm.sh/release-namespace: default
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: app-deployer
      containers:
        - name: backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          env:
            - name: MONGO_URI
              value: "mongodb+srv://mohanadnasar:1QA2WS3ED4RF@dhbw-appstore.6z23fql.mongodb.net/?retryWrites=true&w=majority&appName=DHBW-AppStore/test"
