apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app.kubernetes.io/managed-by: Helm
    app: frontend
  annotations:
    meta.helm.sh/release-name: appstore-chart
    meta.helm.sh/release-namespace: default
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
          env:
            - name: REACT_APP_BACKEND_URL
              value: "http://{{ .Values.ingress.host }}"
          ports:
            - containerPort: 80
