apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app.kubernetes.io/managed-by: Helm   
    app.kubernetes.io/name: mongodb     
  annotations:
    meta.helm.sh/release-name: appstore-chart        
    meta.helm.sh/release-namespace: default         
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
