apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-deployer-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: {{ include "appstore-chart.serviceAccountName" . }}
  namespace: default
roleRef:
  kind: Role
  name: app-deployer-role
  apiGroup: rbac.authorization.k8s.io
